### ISSUE TITLE
Comparing String fails

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#105]
I have a Json:
`final String json = "{\"myString\":\"962862650\"}";`
then:
`JsonFluentAssert.assertThatJson(json).node("myString").isEqualTo("962862650");`

throws:
```
20:39:45.942 [pool-1-thread-1] [debug] net.javacrumbs.jsonunit.difference.diff - JSON documents are different:
Different value found in node "myString", expected: <962862650> but was: <"962862650">.
20:39:45.942 [pool-1-thread-1] [debug] net.javacrumbs.jsonunit.difference.values - Comparing expected:
962862650
------------
with actual:
"962862650"
```
but it shouldn't because `"962862650"` it's not a number!

**Comment by lukas-krecan** [comment]
As Javadoc of isEqualTo method says: Compares JSON for equality. The expected object is converted to JSON before comparison. Ignores order of sibling nodes and whitespaces. Please note that if you pass a String, it's parsed as JSON which can lead to an unexpected behavior. If you pass in "1" it is parsed as a JSON containing integer 1. If you compare it with a string it fails due to a different type. If you want to pass in real string you have to quote it "\"1\"" or use isStringEqualTo(String). If the string parameter is not a valid JSON, it is quoted automatically.

**Comment by eximius313** [comment]
Look closer at my example: I'm not passing the String `myStr = "1"` but as you can see `myStr = "\"1\""` which is undoubtedly JSON String and should be treated like that.
