### ISSUE TITLE
[Feature] Ignoring fields with keys and values

### ISSUE THREAD

**Issue by viclovsky** [lukas-krecan/JsonUnit#128]
Hi,
JsonUnit have method whenIgnoringPaths, that ignores only value of fields.
It will be great to have additional method that ignores whole field with key and value. It will be usefull, if some fields are loaded asynchronously.

**Comment by lukas-krecan** [comment]
Hi, thanks. I do not get it, I think that whenIgnoringPaths ignores the whole field, can you please provide an example?

**Comment by viclovsky** [comment]
Option IGNORING_EXTRA_FIELD and whenIgnoringPaths ignores the whole field only for extra fields. Unfortunately It not works for missing fields.

**Comment by lukas-krecan** [comment]
I understand, thanks

**Comment by lukas-krecan** [comment]
One more question, why do you have `\"ignored\": 1` in the expected value? If you remove it, IGNORING_EXTRA_FIELD should help.

**Comment by viclovsky** [comment]
> One more question, why do you have \"ignored\": 1 in the expected value?

I get expected value from remote source (stable service in the same enviroment) in my case.

> If you remove it, IGNORING_EXTRA_FIELD should help.

It should help. But to my mind it will be better solution if JsoUnit supports the feature from the box.

**Comment by lukas-krecan** [comment]
Hi, I thought I understand the issue so I went to implement it. I started to write tests and realize I still do not understand. See the following tests
        // "ignored" is missing from actual JSON, test passes
        assertThatJson("{\"root\":{\"test\":1}}")
            .whenIgnoringPaths("root.ignored")
            .isEqualTo("{\"root\":{\"test\":1}}");

         // "ignored" is returned by the service but is ignored, test passes
        assertThatJson("{\"root\":{\"test\":1, \"ignored\": 1}}")
                    .whenIgnoringPaths("root.ignored")
                    .isEqualTo("{\"root\":{\"test\":1}}");

**Comment by viclovsky** [comment]
See the following test:
```
@Test
    public void shouldHasNoDiffWithStableService() {
        //get actual value from my service
        Object actual = getActualValue();
        //get expected value from remote source (it may be stable service in the same enviroment, for example) with "root.ignored" field. It is loaded asynchronously.
        Object expected = getExpectedValue();
        //I want ignore "root.ignored" field in expected value
        assertThatJson(object).whenIgnoringPaths("root.ignored").isEqualTo(expected);
    }  
```
Unfortunately It does not work.
Output:
```
java.lang.AssertionError: JSON documents are different:
Different keys found in node "root", expected: <[ignored, ...]> but was: <[...]>. Missing: "root.ignored"
```

For example
```
@Test
    public void pathShouldBeIgnoredForMissingKey() {
        assertThatJson("{\"root\":{\"test\":1}}").whenIgnoringPaths("root.ignored").isEqualTo(
                "{\"root\":{\"test\":1, \"ignored\": 1}}"
        );
    }
```
Output:
```
java.lang.AssertionError: JSON documents are different:
Different keys found in node "root", expected: <[ignored, test]> but was: <[test]>. Missing: "root.ignored"
```

Sorry for the late answer

**Comment by lukas-krecan** [comment]
I see, both values are from a remote service. What an interesting use-case. The library is built around assumption that the "expected" value is known beforehand so the comparison is asymmetric.  I will think about it, but I am afraid that the requirement goes to far against the assumptions the library is built on.

**Comment by galactoise** [comment]
Hi Lukas.

I've found myself in need of this same feature, although for a different reason than in the original request. In my case, we are doing strict contract validation of responses from the services we are testing. Recently, however, a new field was added to the response body. This one field is non-deterministic by its very nature, and in cases where a field's value is null, the key is not included in the response. So, what we need is the ability to say:

"Do not fail because of this path, regardless of whether it is present on the actual output."

We are aware of the IGNORING_EXTRA_FIELDS option, and in fact that's what we're using as a workaround right now, but that is problematic in that it has global scale. Specifically:

`
// "ignored" is missing from actual JSON, test passes
    assertThatJson("{\"root\":{\"test\":1}}")
        .whenIgnoringPaths("root.ignored")
        .isEqualTo("{\"root\":{\"test\":1}}");

     // "ignored" is returned by the service but is ignored, test passes
    assertThatJson("{\"root\":{\"test\":1, \"ignored\": 1}}")
                .whenIgnoringPaths("root.ignored")
                .isEqualTo("{\"root\":{\"test\":1}}");

     // "otherSurpriseField" is returned by the service but is ignored, test passes, needs to fail
    assertThatJson("{\"root\":{\"test\":1, \"otherSurpriseField\": 1}}")
                .whenIgnoringPaths("root.ignored")
                .isEqualTo("{\"root\":{\"test\":1}}");
`

IGNORING_EXTRA_FIELDS makes it so that we no longer recognize when ANY new field was added unexpectedly, which means we can no longer validate this contract strictly.

It seems like there are a couple possible ways to implement this - the first would be a 2-parameter overload of whenIgnoringPath with the second parameter being a boolean saying whether or not to also ignore the key; a second good option could be to potentially have some sort of wildcard replacement token in the expected field string itself which is more than just "match any value", but instead would be "match any value, null, or field not present". The first option feels cleaner, but the second option would be in line with a similar feature request made here: https://github.com/lukas-krecan/JsonUnit/issues/168

**Comment by lukas-krecan** [comment]
@galactoise Hi, thanks. I will most likely implement the feature, I just need to understand why current `whenIgnoringPath` is not sufficient for your use case?

```
       assertThatJson("{\"root\":{\"test\":1, \"ignored\": 1}}")
            .withConfiguration(c -> c.whenIgnoringPaths("root.ignored"))
            .isEqualTo("{\"root\":{\"test\":1}}");
```

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/JsonUnit/pull/173

**Comment by galactoise** [comment]
@lukas-krecan looks like you nailed it - the unit tests you developed for #173 - specifically `shouldIgnoreElementIfMissing` - do a great job of showing the exact situation we're dealing with, and `json-unit.ignore-element` is a perfectly elegant solution that I believe covers all of our current cases.

**Comment by lukas-krecan-lt** [comment]
Cool, can you please explain why current whenIgnoringPath is not sufficient for your use-case. I just would like to understand it.

**Comment by galactoise** [comment]
You know, I'm now questioning my claim that whenIgnoringPath is insufficient. I think maybe I was misinterpreting viclovsky's (and andrew-qiu's, in #168) seemingly incorrect arguments as coming from you. It wasn't until I reread this thread and saw your note about the expected and actual being asymmetric for this feature that I really understood how the feature worked.

So, given the choice, the way you've implemented json-unit.ignore-element would still be our preference, as it fits much more cleanly into our test patterns, but if it's preferable to have only a single way of configuring this ignore, I think we'd be fine trying to work with the whenIgnoringPaths approach. If you go that route, I might recommend calling out the nuance of how whenIgnoringPath works in the readme, as the first thing google led me to was the various issues people filed here.

**Comment by lukas-krecan** [comment]
Cool, thanks, I will clarify the documentation and release json-unit.ignore-element support
