### ISSUE TITLE
Please move inPath to JsonAssert

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#136]
Currently `inPath` is in `ConfigurableJsonAssert`, which causes big problem, because `ConfigurableJsonAssert` extends `JsonAssert`, so `SELF` for `ConfigurableJsonAssert` is not `ConfigurableJsonAssert` but `JsonAssert`.

Consequence?
If you do `assertThatJson("foo").inPath` it's fine, but `assertThatJson("foo").describedAs("bar").inPath` does not compile

**Comment by lukas-krecan** [comment]
I am really afraid to move it to JsonAssert since it would lead to madness like `assertThatJson().node().inPath().node().inPath()` which I am not willing support yet. I understand your problem, it might get fixed by something like this https://github.com/lukas-krecan/JsonUnit/pull/139/files after I untangle all generics gotchas.

**Comment by eximius313** [comment]
1) Indeed `Generics` could solve `describedAs` problem
2) I see `assertThatJson().node().inPath().node().inPath()` as perfectly fine use case

If `node("foo").node("bar")` works fine and `inPath` works fine, then why combination of theese shall not work?

**Comment by lukas-krecan** [comment]
It is a fine use case but there is a huge risk of unintended consequences.

**Comment by eximius313** [comment]
I can be your volunteer tester :D
