### ISSUE TITLE
JsonAssert.assertJsonStructureEquals succeeds when comparing against null as actual value

### ISSUE THREAD

**Issue by lukemueller** [lukas-krecan/JsonUnit#29]
When comparing an expected structure against null the assertion passes. This seems like a false positive to me.

``` Java
import org.junit.Test;
import static net.javacrumbs.jsonunit.JsonAssert.assertJsonStructureEquals;

public class MyTestCase {

    @Test
    public void myTest() {
        // This assertion will pass
        assertJsonStructureEquals(
            "{" +
                "  \"key\": \"value\"," +
                "  \"other\": \"another\"" +
                "}",
            null
        );
    }
}
```

**Comment by lukas-krecan** [comment]
You are right, assertJsonStructureEquals is too lenient, unfortunately I can not change its behaviour due to backward compatibility reasons. Luckily, there is a better alternative

         assertJsonEquals(
            "{" +
                "  \"key\": \"value\"," +
                "  \"other\": \"another\"" +
                "}",
            null, when(Option.IGNORING_VALUES)
        );

Please let me know, if it solves you problem. I have removed assertJsonStructureEquals from the documentation and replace it with IGNORING_VALUES option instead.
