### ISSUE TITLE
Comparison of jsons (with tolerance) fails for numbers, when any option is provided

### ISSUE THREAD

**Issue by priyesh25** [lukas-krecan/JsonUnit#51]
**Passes:**
    JsonAssert.setTolerance(0.01);
    assertJsonEquals("{\"test\":1}", "{\"test\":1.009}");

**Passes:**
     assertJsonEquals("{\"test\":1}", "{\"test\":1,\"extra\":2323}", when(IGNORING_EXTRA_FIELDS));

**Fails:**
    JsonAssert.setTolerance(0.01);
     assertJsonEquals("{\"test\":1}", "{\"test\":1.009}", when(IGNORING_EXTRA_FIELDS)); 

Combining withTolerance and when Option fails.

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. JsonAssert.setTolerance(0.01) is an obsolete static configuration which get's overriden be local configuration provided by "when". You can set tolerance locally by using when(..).withTolerance(..) or you can set IGNORING_EXTRA_FIELDS globally by JsonAssert.setOptions(). I admit it's a bit confusing but it's hard to change due to backward compatibility.

**Comment by priyesh25** [comment]
Thanks for the response. So its either both (tolerance and options) global or both local.
Going with both global for now. Thanks :)
