### ISSUE TITLE
Consider switching to android-json or similar library

### ISSUE THREAD

**Issue by syakovyn** [lukas-krecan/JsonUnit#56]
Hi,

According to https://github.com/spring-projects/spring-boot/issues/8706, it might be worth considering switching from `json` to `android-json` or a similar library for a licensing reason.

Thanks,
Serhiy

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. Will try to support both versions of json.org

**Comment by lukas-krecan** [comment]
Unfortunately androidjson library is really old (and crappy) and does not support some of the features I need (like converting a map containing BigDecimals to JsonObject)  In other words, it seems that it's not worth the effort to support it (see the commit where I tried https://github.com/lukas-krecan/JsonUnit/commit/8bf771f3c9bb2c7c6c667272ed0a1a7eb3bf571e) But, as JsonUnit is trying to use a best library it can find, you may try to add another JSON library (as Jackson 2) into your test dependencies and it should use it instead of json.org.
