### ISSUE TITLE
Diff pattern lost when ignoring array order

### ISSUE THREAD

**Issue by hamza-amami** [lukas-krecan/JsonUnit#57]
Hello

I'm having a small issue while comparing two json ;

Actually i'm used to catch the assertion message in this pattern : Expected <> but was <>
When i'm using `IGNORING_ARRAY_ORDER`, I catch an array excpetion containing the whole array, and not only the difference fields.

Is there a way to keep the same pattern and using ignoring array order

Thanks

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. If you ignore array order the comparison is much more difficult (see the discussion in https://github.com/lukas-krecan/JsonUnit/issues/28) Since you are not the only one asking for this, I will try to implement something for the special case, when only one difference is found.

**Comment by lukas-krecan** [comment]
Better diff reporting for unordered arrays with single difference released in 1.21.0. Enjoy
