### ISSUE TITLE
Asserting with rest-assured

### ISSUE THREAD

**Issue by afcbpeter** [lukas-krecan/JsonUnit#73]
Hi this isn't an issue with jsonUnit more with my understanding of how it is suppose to work. 

I'm currently using rest assured and Json-unit to assert a local json file against the requested rest assured response. I currently have a before class method with my base uri. I am struggling with the test. I know I'm way off at the moment. I'm struggling with the json-unit documentation. Do I need to input a file first? I'm not really sure I follow the documentation that well? Im definitely missing some pieces. Would anyone be able to point me in the right direction?     

```
@Test     
public void ApiaryTest1() throws Exception {          

when()                  
.get("/test")                
 .then()                 
.statusCode(200);  
// compares two JSON documents        
 assertJsonEquals("expected/test.json", "http://apiary/test");
}
```

**Comment by lukas-krecan-lt** [comment]
Hi. To load the expected document, you can use https://github.com/lukas-krecan/JsonUnit/blob/master/json-unit-core/src/main/java/net/javacrumbs/jsonunit/core/util/ResourceUtils.java. Then you have to integrate it with rest-assured. Since rest-assured supports Hamcrest matchers, it should be possible to write something like this

`get("/lotto").then().body("lotto.winners.winnerId", jsonEquals(resource("expected/test.json")))`

But I have never tested such combination so I have no idea how it plays together. Good luck
