### ISSUE TITLE
Bug matching number as strings

### ISSUE THREAD

**Issue by jpnovais** [lukas-krecan/JsonUnit#836]
**Describe the bug**

**Lib version:** `net.javacrumbs.json-unit:json-unit-assertj:3.4.1`

When the JSON has value as string that is a number, assertj wrong fails the assertion.

#### Assertion fail is expected to pass

```kotlin
assertThatJson("""{"id":123, "version":"1.2"}""") {
    node("version").isEqualTo("1.2") // Fails it shall pass
 }
```

The **version** assertion shall pass but fails with
```
org.opentest4j.AssertionFailedError: JSON documents are different:
Different value found in node "version", expected: <1.2> but was: <"1.2">.
```
#### Assertions expected to fail 

```kotlin
assertThatJson("""{"id":123, "version":"1.2"}""") {
  node("version").isEqualTo(1.2) // expected to fail, types are different String vs Number
}

assertThatJson("""{"id":123, "version":1.2}""") {
  node("version").isEqualTo("1.2") // expected to fail, types are different String vs Number
}
```

**Comment by lukas-krecan** [comment]
Hi, `isEqualTo` tries to parse as a JSON and if it succeeds, the JSON is used - for example this works `isEqualTo("{a: 1}")`. "1.2" is a string containing valid JSON `1.2`. Is it surprising? Maybe. Is it soemthing I will be able to change without breaking everybody's tests? No. Of you want to be explicit, just write `node("version").isString().isEqualTo(1.2)`

**Comment by edudar-chwy** [comment]
I second this request. While `1.2` is a valid JSON, the intent of such a test (and I found this issue because I have a few as well) is clear that `"1.2"` is not considered a JSON for node value and should be treated as a string instead of parsed as a float. Breaking everybody's (probably not) is not a good thing; it should be possible to introduce a configuration option like Jackson does and have it enabled/disabled by default to preserve current behavior.

**Comment by lukas-krecan** [comment]
Configuration option is tricky in a library like JsonUnit. In Jackson you have the object mapper you can configure. In JsonUnit or AssertJ you have just buch of static method. So you either have to apply the configuraiton over and over againm or use a static variable.

Would introducing method `isStringEqualTo(expected)` help you to disambiguate?
